In [3]:
#1.kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2.veri onisleme
#2.1.veri yukleme
veriler = pd.read_csv('veriler/veriler.csv')
#pd.read_csv("veriler.csv")
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [4]:
x = veriler.iloc[:,1:4].values #bağımsız değişkenler
y = veriler.iloc[:,4:].values #bağımlı değişken

In [5]:
#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split

x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=0)


In [6]:
#verilerin olceklenmesi
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [7]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(X_train,y_train)

y_pred = logr.predict(X_test)
print(y_pred)
print(y_test)

['e' 'e' 'e' 'e' 'k' 'e' 'e' 'k']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[0 1]
 [6 1]]


In [ ]:
# Başarı Oranı
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
# Sonuç : 0.739961759082218
print(accuracy)

In [7]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1, metric='minkowski')
knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1 0]
 [1 6]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


In [ ]:
# Başarı Oranı
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
# Sonuç : 0.739961759082218
print(accuracy)

In [8]:
from sklearn.svm import SVC
svc = SVC(kernel='rbf')
svc.fit(X_train,y_train)

y_pred = svc.predict(X_test)

cm = confusion_matrix(y_test,y_pred)
print('SVC')
print(cm)

SVC
[[1 0]
 [5 2]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# Başarı Oranı
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
# Sonuç : 0.739961759082218
print(accuracy)

In [9]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)

cm = confusion_matrix(y_test,y_pred)
print('GNB')
print(cm)

GNB
[[0 1]
 [6 1]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# Başarı Oranı
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
# Sonuç : 0.739961759082218
print(accuracy)

In [10]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy')

dtc.fit(X_train,y_train)
y_pred = dtc.predict(X_test)

cm = confusion_matrix(y_test,y_pred)
print('DTC')
print(cm)


DTC
[[1 0]
 [1 6]]


In [ ]:
# Başarı Oranı
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
# Sonuç : 0.739961759082218
print(accuracy)

In [24]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10, criterion = 'entropy')
rfc.fit(X_train,y_train)

y_pred = rfc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
print('RFC')
print(cm)

RFC
[[1 0]
 [0 7]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
# Başarı Oranı
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
# Sonuç : 0.739961759082218
print(accuracy)

In [25]:
# 7. ROC , TPR, FPR değerleri 

y_proba = rfc.predict_proba(X_test) # predict_proba X_test'in tahmin olasılıklarını verir. 
print(y_test)
print(y_proba)

[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]
[[0.4 0.6]
 [0.1 0.9]
 [0.1 0.9]
 [0.1 0.9]
 [0.9 0.1]
 [0.1 0.9]
 [0.1 0.9]
 [0.1 0.9]]


**y_proba kısmında 2 tane sütun çıkıyor bu sütunlar, Solda erkek sağda kız olarak belirlenmiştir. Bize 1'nci satırda şunu söyler, %40 erkek sınıflandırdım, %60 kadın sınıflandırdım.**

In [34]:
from sklearn import metrics

fpr , tpr , thold = metrics.roc_curve(y_test,y_proba[:,0],pos_label='e')

print(fpr) # False Pozitif Rate
print(tpr) # True Pozitif Rate
print(thold) # Threshold

[0.         0.         0.14285714 1.        ]
[0. 1. 1. 1.]
[1.9 0.9 0.4 0.1]
